{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b510f5c7-e882-4c8b-91e6-1e3185d9c843",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import re\n",
    "import string\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from nltk import pos_tag, word_tokenize\n",
    "from collections import Counter\n",
    "import textstat\n",
    "from textblob import TextBlob\n",
    "\n",
    "# ---------- NLTK setup (runs on Streamlit Cloud boot) ----------\n",
    "@st.cache_resource\n",
    "def setup_nltk():\n",
    "    for pkg in ['stopwords', 'punkt', 'punkt_tab',\n",
    "                'averaged_perceptron_tagger', 'averaged_perceptron_tagger_eng']:\n",
    "        nltk.download(pkg, quiet=True)\n",
    "    return True\n",
    "\n",
    "setup_nltk()\n",
    "stop_words = set(stopwords.words('english'))\n",
    "\n",
    "# ---------- Load model ----------\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    return joblib.load('fake_news_model.pkl')\n",
    "\n",
    "model = load_model()\n",
    "# ---------- Helper functions ----------\n",
    "def clean_text(text):\n",
    "    if pd.isna(text):\n",
    "        return \"\"\n",
    "    text = str(text).lower()\n",
    "    text = re.sub(r'http\\S+|www\\S+', '', text)\n",
    "    text = re.sub(r'[^a-zA-Z\\s]', '', text)\n",
    "    text = re.sub(r'\\s+', ' ', text).strip()\n",
    "    return text\n",
    "\n",
    "def get_pos_distribution(text):\n",
    "    default = {\n",
    "        'pos_noun_ratio': 0, 'pos_verb_ratio': 0, 'pos_adj_ratio': 0,\n",
    "        'pos_adv_ratio': 0, 'pos_pron_ratio': 0, 'pos_propn_ratio': 0,\n",
    "        'pos_num_ratio': 0, 'pos_other_ratio': 0\n",
    "    }\n",
    "    if not text or len(text.split()) < 3:\n",
    "        return default, []\n",
    "    try:\n",
    "        tokens = word_tokenize(text)\n",
    "        tags = pos_tag(tokens)\n",
    "    except Exception:\n",
    "        return default, []\n",
    "    total = len(tags) if tags else 1\n",
    "    counts = Counter(tag for _, tag in tags)\n",
    "\n",
    "    def ratio(prefixes):\n",
    "        return sum(v for k, v in counts.items() if any(k.startswith(p) for p in prefixes)) / total\n",
    "\n",
    "    dist = {\n",
    "        'pos_noun_ratio':  ratio(['NN']),\n",
    "        'pos_verb_ratio':  ratio(['VB']),\n",
    "        'pos_adj_ratio':   ratio(['JJ']),\n",
    "        'pos_adv_ratio':   ratio(['RB']),\n",
    "        'pos_pron_ratio':  ratio(['PRP']),\n",
    "        'pos_propn_ratio': ratio(['NNP']),\n",
    "        'pos_num_ratio':   ratio(['CD']),\n",
    "    }\n",
    "    dist['pos_other_ratio'] = max(0.0, 1 - sum(dist.values()))\n",
    "    return dist, tags\n",
    "\n",
    "def extract_features(text):\n",
    "    if not text or len(text.split()) < 3:\n",
    "        base = {k: 0 for k in [\n",
    "            'exclamation_count','question_count','all_caps_ratio',\n",
    "            'punctuation_ratio','readability_flesch','sentiment_polarity',\n",
    "            'sentiment_subjectivity','avg_word_length','unique_word_ratio',\n",
    "            'stopword_ratio']}\n",
    "        pos_dist, _ = get_pos_distribution(text)\n",
    "        base.update(pos_dist)\n",
    "        return base\n",
    "\n",
    "    words = text.split()\n",
    "    total_chars = len(text)\n",
    "    exclamation = text.count('!')\n",
    "    question    = text.count('?')\n",
    "    caps_words  = sum(1 for w in words if w.isupper() and len(w) > 2)\n",
    "    all_caps_ratio = caps_words / max(len(words), 1)\n",
    "    punct_chars = sum(1 for c in text if c in string.punctuation)\n",
    "    punct_ratio = punct_chars / max(total_chars, 1)\n",
    "\n",
    "    try:\n",
    "        flesch = textstat.flesch_reading_ease(text)\n",
    "    except Exception:\n",
    "        flesch = 0\n",
    "\n",
    "    blob = TextBlob(text)\n",
    "    polarity     = blob.sentiment.polarity\n",
    "    subjectivity = blob.sentiment.subjectivity\n",
    "\n",
    "    avg_word_len = np.mean([len(w) for w in words]) if words else 0\n",
    "    unique_ratio = len(set(words)) / max(len(words), 1)\n",
    "    stop_ratio   = sum(1 for w in words if w in stop_words) / max(len(words), 1)\n",
    "\n",
    "    features = {\n",
    "        'exclamation_count': exclamation,\n",
    "        'question_count': question,\n",
    "        'all_caps_ratio': all_caps_ratio,\n",
    "        'punctuation_ratio': punct_ratio,\n",
    "        'readability_flesch': flesch,\n",
    "        'sentiment_polarity': polarity,\n",
    "        'sentiment_subjectivity': subjectivity,\n",
    "        'avg_word_length': avg_word_len,\n",
    "        'unique_word_ratio': unique_ratio,\n",
    "        'stopword_ratio': stop_ratio\n",
    "    }\n",
    "    pos_dist, _ = get_pos_distribution(text)\n",
    "    features.update(pos_dist)\n",
    "    return features\n",
    "\n",
    "def get_problem_flags(f):\n",
    "    flags = []\n",
    "    if f['exclamation_count'] > 3:\n",
    "        flags.append(f\"Excessive exclamation marks ({f['exclamation_count']})\")\n",
    "    if f['question_count'] > 2:\n",
    "        flags.append(f\"High rhetorical questions ({f['question_count']})\")\n",
    "    if f['all_caps_ratio'] > 0.15:\n",
    "        flags.append(f\"High ALL-CAPS ratio ({f['all_caps_ratio']:.1%})\")\n",
    "    if f['readability_flesch'] < 30:\n",
    "        flags.append(f\"Low readability (Flesch: {f['readability_flesch']:.0f})\")\n",
    "    if f['sentiment_polarity'] < -0.3:\n",
    "        flags.append(f\"Strong negative sentiment ({f['sentiment_polarity']:.2f})\")\n",
    "    if f['sentiment_subjectivity'] > 0.6:\n",
    "        flags.append(f\"Highly subjective ({f['sentiment_subjectivity']:.2f})\")\n",
    "    if f['unique_word_ratio'] < 0.6:\n",
    "        flags.append(f\"Low lexical diversity ({f['unique_word_ratio']:.2f})\")\n",
    "    if f['pos_pron_ratio'] > 0.12:\n",
    "        flags.append(f\"High pronoun usage ({f['pos_pron_ratio']:.1%}) — vague attribution\")\n",
    "    if f['pos_adj_ratio'] > 0.10:\n",
    "        flags.append(f\"High adjective density ({f['pos_adj_ratio']:.1%}) — opinion-heavy\")\n",
    "    if f['pos_adv_ratio'] > 0.08:\n",
    "        flags.append(f\"High adverb density ({f['pos_adv_ratio']:.1%}) — intensifiers/hyperbole\")\n",
    "    return flags\n",
    "\n",
    "POS_LABELS = {\n",
    "    'pos_noun_ratio':  'Nouns (NN*)',\n",
    "    'pos_verb_ratio':  'Verbs (VB*)',\n",
    "    'pos_adj_ratio':   'Adjectives (JJ*)',\n",
    "    'pos_adv_ratio':   'Adverbs (RB*)',\n",
    "    'pos_pron_ratio':  'Pronouns (PRP*)',\n",
    "    'pos_propn_ratio': 'Proper Nouns (NNP*)',\n",
    "    'pos_num_ratio':   'Numbers (CD)',\n",
    "    'pos_other_ratio': 'Other'\n",
    "}\n",
    "\n",
    "# ---------- UI ----------\n",
    "st.set_page_config(page_title=\"LIAR Fake News Detector\", page_icon=\"📰\", layout=\"wide\")\n",
    "st.title(\"📰 LIAR Fake News Detector\")\n",
    "st.markdown(\"Paste a political claim below. The system analyses **linguistic consistency**, \"\n",
    "            \"**POS patterns**, and (optionally) **speaker metadata**.\")\n",
    "\n",
    "with st.sidebar:\n",
    "    st.header(\"About\")\n",
    "    st.info(\"Trained on 12,836 PolitiFact statements (LIAR dataset). \"\n",
    "            \"Binary classification: fake vs. real. \"\n",
    "            \"Realistic accuracy on LIAR is ~0.70–0.85.\")\n",
    "\n",
    "user_title = st.text_input(\"Statement Title (optional)\", placeholder=\"Enter headline...\")\n",
    "user_text  = st.text_area(\"Statement / Claim\", height=200,\n",
    "                          placeholder=\"Paste the claim or statement here...\")\n",
    "\n",
    "# ---------- Optional speaker/context metadata (defaults are neutral) ----------\n",
    "with st.expander(\"Optional: Speaker & context metadata (improves accuracy)\"):\n",
    "    col_a, col_b, col_c = st.columns(3)\n",
    "    with col_a:\n",
    "        party = st.selectbox(\"Speaker party\",\n",
    "                             ['unknown', 'republican', 'democrat', 'independent', 'none', 'libertarian'])\n",
    "    with col_b:\n",
    "        job_title = st.selectbox(\"Speaker job title\",\n",
    "                                 ['unknown', 'president', 'senator', 'representative',\n",
    "                                  'governor', 'candidate', 'pundit', 'talk show host',\n",
    "                                  'radio host', 'columnist', 'activist'])\n",
    "    with col_c:\n",
    "        subject_primary = st.selectbox(\"Primary subject\",\n",
    "                                       ['unknown', 'economy', 'healthcare', 'immigration',\n",
    "                                        'taxes', 'education', 'jobs', 'elections',\n",
    "                                        'terrorism', 'gun control', 'abortion'])\n",
    "    context_choice = st.selectbox(\"Context\",\n",
    "                                  ['unknown', 'speech', 'debate', 'rally', 'interview',\n",
    "                                   'ad', 'tweet', 'news release'])\n",
    "    speaker_reliability = st.slider(\"Speaker reliability score (-1 = unreliable, +1 = reliable)\",\n",
    "                                    min_value=-1.0, max_value=1.0, value=0.0, step=0.05)\n",
    "\n",
    "if st.button(\"🔍 Analyze\", type=\"primary\"):\n",
    "    if not user_text or len(user_text.split()) < 5:\n",
    "        st.warning(\"Please enter at least 5 words of statement text.\")\n",
    "    else:\n",
    "        clean_title = clean_text(user_title)\n",
    "        clean_body  = clean_text(user_text)\n",
    "        full_text   = (clean_title + ' ' + clean_body).strip()\n",
    "\n",
    "        feats = extract_features(user_text)\n",
    "\n",
    "        # ---- Fill in the metadata columns the model now expects ----\n",
    "        feats.update({\n",
    "            # Speaker credit history — defaults to zeros when unknown\n",
    "            'count_barely_true': 0,\n",
    "            'count_false': 0,\n",
    "            'count_half_true': 0,\n",
    "            'count_mostly_true': 0,\n",
    "            'count_pants_fire': 0,\n",
    "            'truth_ratio': max(0.0, speaker_reliability),\n",
    "            'fake_ratio': max(0.0, -speaker_reliability),\n",
    "            'speaker_reliability': speaker_reliability,\n",
    "\n",
    "            # Context flags\n",
    "            'is_debate':       int(context_choice == 'debate'),\n",
    "            'is_rally':        int(context_choice == 'rally'),\n",
    "            'is_interview':    int(context_choice == 'interview'),\n",
    "            'is_ad':           int(context_choice == 'ad'),\n",
    "            'is_tweet':        int(context_choice == 'tweet'),\n",
    "            'is_news_release': int(context_choice == 'news release'),\n",
    "            'is_speech':       int(context_choice == 'speech'),\n",
    "\n",
    "            # Categorical metadata\n",
    "            'party':           party,\n",
    "            'job_title':       job_title,\n",
    "            'subject_primary': subject_primary,\n",
    "        })\n",
    "\n",
    "        input_df = pd.DataFrame([{**{'full_text': full_text}, **feats}])\n",
    "\n",
    "        proba = model.predict_proba(input_df)[0]\n",
    "        pred  = model.predict(input_df)[0]\n",
    "        confidence = proba[pred] * 100\n",
    "\n",
    "        col1, col2 = st.columns([1, 2])\n",
    "\n",
    "        with col1:\n",
    "            if pred == 1:\n",
    "                st.error(f\"### 🚨 Likely FAKE\\n**Confidence: {confidence:.1f}%**\")\n",
    "            else:\n",
    "                st.success(f\"### ✅ Likely REAL\\n**Confidence: {confidence:.1f}%**\")\n",
    "\n",
    "            st.markdown(\"#### Probability Breakdown\")\n",
    "            st.write(f\"Real: {proba[0]*100:.1f}%\")\n",
    "            st.progress(float(proba[0]))\n",
    "            st.write(f\"Fake: {proba[1]*100:.1f}%\")\n",
    "            st.progress(float(proba[1]))\n",
    "\n",
    "        with col2:\n",
    "            st.markdown(\"#### 🚩 Problematic Linguistic Areas\")\n",
    "            flags = get_problem_flags(feats)\n",
    "            if flags:\n",
    "                for flag in flags:\n",
    "                    st.warning(f\"• {flag}\")\n",
    "            else:\n",
    "                st.success(\"No major linguistic red flags detected.\")\n",
    "\n",
    "            st.markdown(\"#### 🧩 POS Tag Distribution\")\n",
    "            pos_data = {POS_LABELS[k]: round(feats[k] * 100, 2) for k in POS_LABELS}\n",
    "            pos_df = pd.DataFrame(list(pos_data.items()),\n",
    "                                  columns=[\"POS Category\", \"Percentage (%)\"])\n",
    "            st.dataframe(pos_df, use_container_width=True, hide_index=True)\n",
    "            st.bar_chart(pos_df.set_index(\"POS Category\"))\n",
    "\n",
    "            with st.expander(\"🔠 Sample POS-Tagged Tokens (first 25)\"):\n",
    "                _, tags = get_pos_distribution(user_text)\n",
    "                if tags:\n",
    "                    st.dataframe(pd.DataFrame(tags[:25], columns=[\"Token\", \"POS Tag\"]),\n",
    "                                 use_container_width=True, hide_index=True)\n",
    "                else:\n",
    "                    st.info(\"Not enough text to extract POS tags.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2025.12-py312",
   "language": "python",
   "name": "conda-env-anaconda-2025.12-py312-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
